package io.specmatic.core.utilities

enum class TrackingFeature {
    BACKWARD_COMPATIBILITY_CHECK, IMPORT_FROM_WSDL, IMPORT_FROM_STUB, IMPORT_FROM_POSTMAN, PROXY, EXAMPLE_VALIDATION, STUB_REQUEST_SERVED, TEST_EXECUTED;
}
