openapi: 3.0.1
info:
  title: Random
  version: "1"
paths:
  /random:
    post:
      summary: Random
      parameters: []
      requestBody:
        content:
          application/json:
            schema:
              required:
              - id
              properties:
                id:
                  type: number
      responses:
        "200":
          description: Random
          content:
            text/plain:
              schema:
                type: string