package io.specmatic.stub

import io.specmatic.core.value.JSONObjectValue

/**
 * Hook for transforming responses generated by the stub before they are sent back to the caller.
 *
 * The hook receives both the request and response in Specmatic-style JSON format:
 * ```json
 * {
 *   "http-request": {
 *     "method": "GET",
 *     "path": "/api/endpoint",
 *     "query": { "param": "value" },
 *     "headers": { "header": "value" },
 *     "body": { ... }
 *   },
 *   "http-response": {
 *     "status": 200,
 *     "headers": { "header": "value" },
 *     "body": { ... }
 *   }
 * }
 * ```
 *
 * The hook should return the transformed JSON in the same format.
 * If null is returned, the original response is used unchanged.
 */
interface ResponseTransformationHook {
    /**
     * Transform the stub response before it is sent to the caller.
     *
     * @param requestResponseJson The request and response in Specmatic JSON format
     *                           with "http-request" and "http-response" fields
     * @return The transformed request/response JSON, or null to use the original response unchanged
     */
    fun transformResponse(requestResponseJson: JSONObjectValue): JSONObjectValue?
}
