name: Conformance Tests

on:
  push:
    branches: [ "main", "conformance-reporting-in-ci" ]

jobs:
  conformance-tests:
    runs-on: ubuntu-latest
    continue-on-error: true
    permissions:
      pull-requests: write
      contents: write # This is required so that the dependency check can push dependency graph to the github repository
      checks: write # Required for test reporting
    steps:
      - name: Configure Docker Daemon Networking
        uses: docker/setup-docker-action@v5
        with:
          # the default address pools only allow upto 32 bridge networks. We create smaller ranges so
          # that we can create many thousands of networks without worrying about running out of space.
          # The conformance tests run and create networks in parallel and sometimes the cleanup of the network
          # takes longer than expected.
          # See also: https://straz.to/2021-09-08-docker-address-pools/
          daemon-config: |
            {
              "default-address-pools": [
                {
                  "base": "172.17.0.0/12",
                  "size": 25
                }
              ]
            }
      - uses: specmatic/specmatic-github-workflows/action-build-gradle@main
        continue-on-error: true
        with:
          gradle-extra-args: "-p conformance-tests -PenableConformanceTests=true" 
          github-token-for-pr-comment: ${{ secrets.GITHUB_TOKEN }} # use the CI token with write permissions to post PR comments

      - name: Publish Test Report
        if: always()
        continue-on-error: true
        uses: mikepenz/action-junit-report@v4
        with:
          report_paths: 'conformance-tests/build/test-results/test/*.xml'
          detailed_summary: false
          include_passed: true
          require_tests: false
