name: Conformance Tests

on:
  push:
    branches: [ "main", "conformance-on-main" ]

jobs:
  conformance-tests:
    runs-on: ubuntu-latest
    continue-on-error: true
    permissions:
      pull-requests: write
      contents: write # This is required so that the dependency check can push dependency graph to the github repository
      checks: write # Required for test reporting
    steps:
      - uses: specmatic/specmatic-github-workflows/action-build-gradle@main
        with:
          gradle-extra-args: "-p conformance-tests -PenableConformanceTests=true --tests \"io.specmatic.conformance_tests.S001Http*\""
          github-token-for-pr-comment: ${{ secrets.GITHUB_TOKEN }} # use the CI token with write permissions to post PR comments
