# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: CI Build

on:
  push:
    branches: [ main, spring-issues ]
  pull_request:
    branches: [ main ]


jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2.3.5
    - name: Set up JDK 1.8
      uses: actions/setup-java@v2
      with:
        java-version: '8.0.282+8'
        distribution: 'adopt'
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build
    - name: Publish to local maven
      run: ./gradlew publishToMavenLocal
    - name: Run maven project to check for Spring 2.3 conflicts
      run: cd spring-2.3-compatibility; mvn -Dspecmatic.version=`cat ../version.properties | cut -d = -f 2` clean test
    - name: Upload artifact
      uses: actions/upload-artifact@v2.2.4
      with:
        name: Specmatic Standalone Executable
        path: application/build/libs/specmatic.jar
