# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: CI Build

on:
  push:
    branches: [ main, spring-issues ]
  pull_request:
    branches: [ main ]


jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 1.8
      uses: actions/setup-java@v3
      with:
        java-version: '8.0.282+8'
        distribution: 'adopt'
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: |
        ./gradlew clean
        git clean -fd
        ./gradlew build
    - name: Publish to local maven
      run: ./gradlew publishToMavenLocal
    - name: Upload core Gradle Log
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: Gradle core Build Log
        path: core/build/reports/
    - name: Upload junit5-support Gradle Log
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: Gradle junit5-support Build Log
        path: junit5-support/build/reports/
    - name: Upload application Gradle Log
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: Gradle application Build Log
        path: application/build/reports/
