# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle
# For creating the release: https://github.com/marketplace/actions/gh-release

name: Release Build

on:
  push:
    tags:
      - '*.*.*'
      - 'SNAPSHOT'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 1.8
      uses: actions/setup-java@v3
      with:
        java-version: '8.0.282+8'
        distribution: 'adopt'
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build
    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        files: application/build/libs/specmatic.jar
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
